[[main]]
  name = "Anthropie"
  url = "/quest-ce-que-lanthropie/"
  weight = 10

[[main]]
  name = "Working Papers"
  url = "/serie-awp/"
  weight = 20

[[main]]
  name = "Livres"
  url = "/livres/"
  weight = 30

[[main]]
  name = "À propos"
  url = "/a-propos/"
  weight = 40

[[main]]
  name = "Contact"
  url = "/contact/"
  weight = 50
